// Autogenerated by jnigen. DO NOT EDIT!

#include <stdint.h>
#include "jni.h"
#include "dartjni.h"

thread_local JNIEnv *jniEnv;
JniContext *jni;

JniContext *(*context_getter)(void);
JNIEnv *(*env_getter)(void);

void setJniGetters(JniContext *(*cg)(void),
        JNIEnv *(*eg)(void)) {
    context_getter = cg;
    env_getter = eg;
}

// com.tencent.mars.xlog.Xlog$XLogConfig
jclass _c_Xlog_XLogConfig = NULL;

jmethodID _m_Xlog_XLogConfig__new0 = NULL;
FFI_PLUGIN_EXPORT
JniResult Xlog_XLogConfig__new0() {
    load_env();
        load_class_global_ref(&_c_Xlog_XLogConfig, "com/tencent/mars/xlog/Xlog$XLogConfig");
    if (_c_Xlog_XLogConfig == NULL) return (JniResult){.value = {.j = 0}, .exception = check_exception()};
    load_method(_c_Xlog_XLogConfig,
      &_m_Xlog_XLogConfig__new0, "<init>", "()V");
    if (_m_Xlog_XLogConfig__new0 == NULL) return (JniResult){.value = {.j = 0}, .exception = check_exception()};
    jobject _result = (*jniEnv)->NewObject(jniEnv, _c_Xlog_XLogConfig, _m_Xlog_XLogConfig__new0);
    return to_global_ref_result(_result);
}

jfieldID _f_Xlog_XLogConfig__level = NULL;
FFI_PLUGIN_EXPORT
JniResult get_Xlog_XLogConfig__level(jobject self_) {
    load_env();
        load_class_global_ref(&_c_Xlog_XLogConfig, "com/tencent/mars/xlog/Xlog$XLogConfig");
    if (_c_Xlog_XLogConfig == NULL) return (JniResult){.value = {.j = 0}, .exception = check_exception()};
    load_field(_c_Xlog_XLogConfig, &_f_Xlog_XLogConfig__level, "level",
      "I");
    int32_t _result = (*jniEnv)->GetIntField(jniEnv, self_, _f_Xlog_XLogConfig__level);
    return (JniResult){.value = {.i = _result}, .exception = check_exception()};
}

FFI_PLUGIN_EXPORT
JniResult set_Xlog_XLogConfig__level(jobject self_, int32_t value) {
    load_env();
        load_class_global_ref(&_c_Xlog_XLogConfig, "com/tencent/mars/xlog/Xlog$XLogConfig");
    if (_c_Xlog_XLogConfig == NULL) return (JniResult){.value = {.j = 0}, .exception = check_exception()};
    load_field(_c_Xlog_XLogConfig, &_f_Xlog_XLogConfig__level, "level",
      "I");
    (*jniEnv)->SetIntField(jniEnv, self_, _f_Xlog_XLogConfig__level, value);
    return (JniResult){.value = {.j = 0}, .exception = check_exception()};
}

jfieldID _f_Xlog_XLogConfig__mode = NULL;
FFI_PLUGIN_EXPORT
JniResult get_Xlog_XLogConfig__mode(jobject self_) {
    load_env();
        load_class_global_ref(&_c_Xlog_XLogConfig, "com/tencent/mars/xlog/Xlog$XLogConfig");
    if (_c_Xlog_XLogConfig == NULL) return (JniResult){.value = {.j = 0}, .exception = check_exception()};
    load_field(_c_Xlog_XLogConfig, &_f_Xlog_XLogConfig__mode, "mode",
      "I");
    int32_t _result = (*jniEnv)->GetIntField(jniEnv, self_, _f_Xlog_XLogConfig__mode);
    return (JniResult){.value = {.i = _result}, .exception = check_exception()};
}

FFI_PLUGIN_EXPORT
JniResult set_Xlog_XLogConfig__mode(jobject self_, int32_t value) {
    load_env();
        load_class_global_ref(&_c_Xlog_XLogConfig, "com/tencent/mars/xlog/Xlog$XLogConfig");
    if (_c_Xlog_XLogConfig == NULL) return (JniResult){.value = {.j = 0}, .exception = check_exception()};
    load_field(_c_Xlog_XLogConfig, &_f_Xlog_XLogConfig__mode, "mode",
      "I");
    (*jniEnv)->SetIntField(jniEnv, self_, _f_Xlog_XLogConfig__mode, value);
    return (JniResult){.value = {.j = 0}, .exception = check_exception()};
}

jfieldID _f_Xlog_XLogConfig__logdir = NULL;
FFI_PLUGIN_EXPORT
JniResult get_Xlog_XLogConfig__logdir(jobject self_) {
    load_env();
        load_class_global_ref(&_c_Xlog_XLogConfig, "com/tencent/mars/xlog/Xlog$XLogConfig");
    if (_c_Xlog_XLogConfig == NULL) return (JniResult){.value = {.j = 0}, .exception = check_exception()};
    load_field(_c_Xlog_XLogConfig, &_f_Xlog_XLogConfig__logdir, "logdir",
      "Ljava/lang/String;");
    jobject _result = (*jniEnv)->GetObjectField(jniEnv, self_, _f_Xlog_XLogConfig__logdir);
    return to_global_ref_result(_result);
}

FFI_PLUGIN_EXPORT
JniResult set_Xlog_XLogConfig__logdir(jobject self_, jobject value) {
    load_env();
        load_class_global_ref(&_c_Xlog_XLogConfig, "com/tencent/mars/xlog/Xlog$XLogConfig");
    if (_c_Xlog_XLogConfig == NULL) return (JniResult){.value = {.j = 0}, .exception = check_exception()};
    load_field(_c_Xlog_XLogConfig, &_f_Xlog_XLogConfig__logdir, "logdir",
      "Ljava/lang/String;");
    (*jniEnv)->SetObjectField(jniEnv, self_, _f_Xlog_XLogConfig__logdir, value);
    return (JniResult){.value = {.j = 0}, .exception = check_exception()};
}

jfieldID _f_Xlog_XLogConfig__nameprefix = NULL;
FFI_PLUGIN_EXPORT
JniResult get_Xlog_XLogConfig__nameprefix(jobject self_) {
    load_env();
        load_class_global_ref(&_c_Xlog_XLogConfig, "com/tencent/mars/xlog/Xlog$XLogConfig");
    if (_c_Xlog_XLogConfig == NULL) return (JniResult){.value = {.j = 0}, .exception = check_exception()};
    load_field(_c_Xlog_XLogConfig, &_f_Xlog_XLogConfig__nameprefix, "nameprefix",
      "Ljava/lang/String;");
    jobject _result = (*jniEnv)->GetObjectField(jniEnv, self_, _f_Xlog_XLogConfig__nameprefix);
    return to_global_ref_result(_result);
}

FFI_PLUGIN_EXPORT
JniResult set_Xlog_XLogConfig__nameprefix(jobject self_, jobject value) {
    load_env();
        load_class_global_ref(&_c_Xlog_XLogConfig, "com/tencent/mars/xlog/Xlog$XLogConfig");
    if (_c_Xlog_XLogConfig == NULL) return (JniResult){.value = {.j = 0}, .exception = check_exception()};
    load_field(_c_Xlog_XLogConfig, &_f_Xlog_XLogConfig__nameprefix, "nameprefix",
      "Ljava/lang/String;");
    (*jniEnv)->SetObjectField(jniEnv, self_, _f_Xlog_XLogConfig__nameprefix, value);
    return (JniResult){.value = {.j = 0}, .exception = check_exception()};
}

jfieldID _f_Xlog_XLogConfig__pubkey = NULL;
FFI_PLUGIN_EXPORT
JniResult get_Xlog_XLogConfig__pubkey(jobject self_) {
    load_env();
        load_class_global_ref(&_c_Xlog_XLogConfig, "com/tencent/mars/xlog/Xlog$XLogConfig");
    if (_c_Xlog_XLogConfig == NULL) return (JniResult){.value = {.j = 0}, .exception = check_exception()};
    load_field(_c_Xlog_XLogConfig, &_f_Xlog_XLogConfig__pubkey, "pubkey",
      "Ljava/lang/String;");
    jobject _result = (*jniEnv)->GetObjectField(jniEnv, self_, _f_Xlog_XLogConfig__pubkey);
    return to_global_ref_result(_result);
}

FFI_PLUGIN_EXPORT
JniResult set_Xlog_XLogConfig__pubkey(jobject self_, jobject value) {
    load_env();
        load_class_global_ref(&_c_Xlog_XLogConfig, "com/tencent/mars/xlog/Xlog$XLogConfig");
    if (_c_Xlog_XLogConfig == NULL) return (JniResult){.value = {.j = 0}, .exception = check_exception()};
    load_field(_c_Xlog_XLogConfig, &_f_Xlog_XLogConfig__pubkey, "pubkey",
      "Ljava/lang/String;");
    (*jniEnv)->SetObjectField(jniEnv, self_, _f_Xlog_XLogConfig__pubkey, value);
    return (JniResult){.value = {.j = 0}, .exception = check_exception()};
}

jfieldID _f_Xlog_XLogConfig__compressmode = NULL;
FFI_PLUGIN_EXPORT
JniResult get_Xlog_XLogConfig__compressmode(jobject self_) {
    load_env();
        load_class_global_ref(&_c_Xlog_XLogConfig, "com/tencent/mars/xlog/Xlog$XLogConfig");
    if (_c_Xlog_XLogConfig == NULL) return (JniResult){.value = {.j = 0}, .exception = check_exception()};
    load_field(_c_Xlog_XLogConfig, &_f_Xlog_XLogConfig__compressmode, "compressmode",
      "I");
    int32_t _result = (*jniEnv)->GetIntField(jniEnv, self_, _f_Xlog_XLogConfig__compressmode);
    return (JniResult){.value = {.i = _result}, .exception = check_exception()};
}

FFI_PLUGIN_EXPORT
JniResult set_Xlog_XLogConfig__compressmode(jobject self_, int32_t value) {
    load_env();
        load_class_global_ref(&_c_Xlog_XLogConfig, "com/tencent/mars/xlog/Xlog$XLogConfig");
    if (_c_Xlog_XLogConfig == NULL) return (JniResult){.value = {.j = 0}, .exception = check_exception()};
    load_field(_c_Xlog_XLogConfig, &_f_Xlog_XLogConfig__compressmode, "compressmode",
      "I");
    (*jniEnv)->SetIntField(jniEnv, self_, _f_Xlog_XLogConfig__compressmode, value);
    return (JniResult){.value = {.j = 0}, .exception = check_exception()};
}

jfieldID _f_Xlog_XLogConfig__compresslevel = NULL;
FFI_PLUGIN_EXPORT
JniResult get_Xlog_XLogConfig__compresslevel(jobject self_) {
    load_env();
        load_class_global_ref(&_c_Xlog_XLogConfig, "com/tencent/mars/xlog/Xlog$XLogConfig");
    if (_c_Xlog_XLogConfig == NULL) return (JniResult){.value = {.j = 0}, .exception = check_exception()};
    load_field(_c_Xlog_XLogConfig, &_f_Xlog_XLogConfig__compresslevel, "compresslevel",
      "I");
    int32_t _result = (*jniEnv)->GetIntField(jniEnv, self_, _f_Xlog_XLogConfig__compresslevel);
    return (JniResult){.value = {.i = _result}, .exception = check_exception()};
}

FFI_PLUGIN_EXPORT
JniResult set_Xlog_XLogConfig__compresslevel(jobject self_, int32_t value) {
    load_env();
        load_class_global_ref(&_c_Xlog_XLogConfig, "com/tencent/mars/xlog/Xlog$XLogConfig");
    if (_c_Xlog_XLogConfig == NULL) return (JniResult){.value = {.j = 0}, .exception = check_exception()};
    load_field(_c_Xlog_XLogConfig, &_f_Xlog_XLogConfig__compresslevel, "compresslevel",
      "I");
    (*jniEnv)->SetIntField(jniEnv, self_, _f_Xlog_XLogConfig__compresslevel, value);
    return (JniResult){.value = {.j = 0}, .exception = check_exception()};
}

jfieldID _f_Xlog_XLogConfig__cachedir = NULL;
FFI_PLUGIN_EXPORT
JniResult get_Xlog_XLogConfig__cachedir(jobject self_) {
    load_env();
        load_class_global_ref(&_c_Xlog_XLogConfig, "com/tencent/mars/xlog/Xlog$XLogConfig");
    if (_c_Xlog_XLogConfig == NULL) return (JniResult){.value = {.j = 0}, .exception = check_exception()};
    load_field(_c_Xlog_XLogConfig, &_f_Xlog_XLogConfig__cachedir, "cachedir",
      "Ljava/lang/String;");
    jobject _result = (*jniEnv)->GetObjectField(jniEnv, self_, _f_Xlog_XLogConfig__cachedir);
    return to_global_ref_result(_result);
}

FFI_PLUGIN_EXPORT
JniResult set_Xlog_XLogConfig__cachedir(jobject self_, jobject value) {
    load_env();
        load_class_global_ref(&_c_Xlog_XLogConfig, "com/tencent/mars/xlog/Xlog$XLogConfig");
    if (_c_Xlog_XLogConfig == NULL) return (JniResult){.value = {.j = 0}, .exception = check_exception()};
    load_field(_c_Xlog_XLogConfig, &_f_Xlog_XLogConfig__cachedir, "cachedir",
      "Ljava/lang/String;");
    (*jniEnv)->SetObjectField(jniEnv, self_, _f_Xlog_XLogConfig__cachedir, value);
    return (JniResult){.value = {.j = 0}, .exception = check_exception()};
}

jfieldID _f_Xlog_XLogConfig__cachedays = NULL;
FFI_PLUGIN_EXPORT
JniResult get_Xlog_XLogConfig__cachedays(jobject self_) {
    load_env();
        load_class_global_ref(&_c_Xlog_XLogConfig, "com/tencent/mars/xlog/Xlog$XLogConfig");
    if (_c_Xlog_XLogConfig == NULL) return (JniResult){.value = {.j = 0}, .exception = check_exception()};
    load_field(_c_Xlog_XLogConfig, &_f_Xlog_XLogConfig__cachedays, "cachedays",
      "I");
    int32_t _result = (*jniEnv)->GetIntField(jniEnv, self_, _f_Xlog_XLogConfig__cachedays);
    return (JniResult){.value = {.i = _result}, .exception = check_exception()};
}

FFI_PLUGIN_EXPORT
JniResult set_Xlog_XLogConfig__cachedays(jobject self_, int32_t value) {
    load_env();
        load_class_global_ref(&_c_Xlog_XLogConfig, "com/tencent/mars/xlog/Xlog$XLogConfig");
    if (_c_Xlog_XLogConfig == NULL) return (JniResult){.value = {.j = 0}, .exception = check_exception()};
    load_field(_c_Xlog_XLogConfig, &_f_Xlog_XLogConfig__cachedays, "cachedays",
      "I");
    (*jniEnv)->SetIntField(jniEnv, self_, _f_Xlog_XLogConfig__cachedays, value);
    return (JniResult){.value = {.j = 0}, .exception = check_exception()};
}

// com.tencent.mars.xlog.Xlog
jclass _c_Xlog = NULL;

jmethodID _m_Xlog__new0 = NULL;
FFI_PLUGIN_EXPORT
JniResult Xlog__new0() {
    load_env();
        load_class_global_ref(&_c_Xlog, "com/tencent/mars/xlog/Xlog");
    if (_c_Xlog == NULL) return (JniResult){.value = {.j = 0}, .exception = check_exception()};
    load_method(_c_Xlog,
      &_m_Xlog__new0, "<init>", "()V");
    if (_m_Xlog__new0 == NULL) return (JniResult){.value = {.j = 0}, .exception = check_exception()};
    jobject _result = (*jniEnv)->NewObject(jniEnv, _c_Xlog, _m_Xlog__new0);
    return to_global_ref_result(_result);
}

jmethodID _m_Xlog__open = NULL;
FFI_PLUGIN_EXPORT
JniResult Xlog__open(uint8_t z,int32_t i,int32_t i1,jobject string,jobject string1,jobject string2,jobject string3) {
    load_env();
        load_class_global_ref(&_c_Xlog, "com/tencent/mars/xlog/Xlog");
    if (_c_Xlog == NULL) return (JniResult){.value = {.j = 0}, .exception = check_exception()};
    load_static_method(_c_Xlog,
      &_m_Xlog__open, "open", "(ZIILjava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)V");
    if (_m_Xlog__open == NULL) return (JniResult){.value = {.j = 0}, .exception = check_exception()};
    (*jniEnv)->CallStaticVoidMethod(jniEnv, _c_Xlog, _m_Xlog__open, z, i, i1, string, string1, string2, string3);
    return (JniResult){.value = {.j = 0}, .exception = check_exception()};
}

jmethodID _m_Xlog__logV = NULL;
FFI_PLUGIN_EXPORT
JniResult Xlog__logV(jobject self_,int64_t j,jobject string,jobject string1,jobject string2,int32_t i,int32_t i1,int64_t j1,int64_t j2,jobject string3) {
    load_env();
        load_class_global_ref(&_c_Xlog, "com/tencent/mars/xlog/Xlog");
    if (_c_Xlog == NULL) return (JniResult){.value = {.j = 0}, .exception = check_exception()};
    load_method(_c_Xlog,
      &_m_Xlog__logV, "logV", "(JLjava/lang/String;Ljava/lang/String;Ljava/lang/String;IIJJLjava/lang/String;)V");
    if (_m_Xlog__logV == NULL) return (JniResult){.value = {.j = 0}, .exception = check_exception()};
    (*jniEnv)->CallVoidMethod(jniEnv, self_, _m_Xlog__logV, j, string, string1, string2, i, i1, j1, j2, string3);
    return (JniResult){.value = {.j = 0}, .exception = check_exception()};
}

jmethodID _m_Xlog__logD = NULL;
FFI_PLUGIN_EXPORT
JniResult Xlog__logD(jobject self_,int64_t j,jobject string,jobject string1,jobject string2,int32_t i,int32_t i1,int64_t j1,int64_t j2,jobject string3) {
    load_env();
        load_class_global_ref(&_c_Xlog, "com/tencent/mars/xlog/Xlog");
    if (_c_Xlog == NULL) return (JniResult){.value = {.j = 0}, .exception = check_exception()};
    load_method(_c_Xlog,
      &_m_Xlog__logD, "logD", "(JLjava/lang/String;Ljava/lang/String;Ljava/lang/String;IIJJLjava/lang/String;)V");
    if (_m_Xlog__logD == NULL) return (JniResult){.value = {.j = 0}, .exception = check_exception()};
    (*jniEnv)->CallVoidMethod(jniEnv, self_, _m_Xlog__logD, j, string, string1, string2, i, i1, j1, j2, string3);
    return (JniResult){.value = {.j = 0}, .exception = check_exception()};
}

jmethodID _m_Xlog__logI = NULL;
FFI_PLUGIN_EXPORT
JniResult Xlog__logI(jobject self_,int64_t j,jobject string,jobject string1,jobject string2,int32_t i,int32_t i1,int64_t j1,int64_t j2,jobject string3) {
    load_env();
        load_class_global_ref(&_c_Xlog, "com/tencent/mars/xlog/Xlog");
    if (_c_Xlog == NULL) return (JniResult){.value = {.j = 0}, .exception = check_exception()};
    load_method(_c_Xlog,
      &_m_Xlog__logI, "logI", "(JLjava/lang/String;Ljava/lang/String;Ljava/lang/String;IIJJLjava/lang/String;)V");
    if (_m_Xlog__logI == NULL) return (JniResult){.value = {.j = 0}, .exception = check_exception()};
    (*jniEnv)->CallVoidMethod(jniEnv, self_, _m_Xlog__logI, j, string, string1, string2, i, i1, j1, j2, string3);
    return (JniResult){.value = {.j = 0}, .exception = check_exception()};
}

jmethodID _m_Xlog__logW = NULL;
FFI_PLUGIN_EXPORT
JniResult Xlog__logW(jobject self_,int64_t j,jobject string,jobject string1,jobject string2,int32_t i,int32_t i1,int64_t j1,int64_t j2,jobject string3) {
    load_env();
        load_class_global_ref(&_c_Xlog, "com/tencent/mars/xlog/Xlog");
    if (_c_Xlog == NULL) return (JniResult){.value = {.j = 0}, .exception = check_exception()};
    load_method(_c_Xlog,
      &_m_Xlog__logW, "logW", "(JLjava/lang/String;Ljava/lang/String;Ljava/lang/String;IIJJLjava/lang/String;)V");
    if (_m_Xlog__logW == NULL) return (JniResult){.value = {.j = 0}, .exception = check_exception()};
    (*jniEnv)->CallVoidMethod(jniEnv, self_, _m_Xlog__logW, j, string, string1, string2, i, i1, j1, j2, string3);
    return (JniResult){.value = {.j = 0}, .exception = check_exception()};
}

jmethodID _m_Xlog__logE = NULL;
FFI_PLUGIN_EXPORT
JniResult Xlog__logE(jobject self_,int64_t j,jobject string,jobject string1,jobject string2,int32_t i,int32_t i1,int64_t j1,int64_t j2,jobject string3) {
    load_env();
        load_class_global_ref(&_c_Xlog, "com/tencent/mars/xlog/Xlog");
    if (_c_Xlog == NULL) return (JniResult){.value = {.j = 0}, .exception = check_exception()};
    load_method(_c_Xlog,
      &_m_Xlog__logE, "logE", "(JLjava/lang/String;Ljava/lang/String;Ljava/lang/String;IIJJLjava/lang/String;)V");
    if (_m_Xlog__logE == NULL) return (JniResult){.value = {.j = 0}, .exception = check_exception()};
    (*jniEnv)->CallVoidMethod(jniEnv, self_, _m_Xlog__logE, j, string, string1, string2, i, i1, j1, j2, string3);
    return (JniResult){.value = {.j = 0}, .exception = check_exception()};
}

jmethodID _m_Xlog__logF = NULL;
FFI_PLUGIN_EXPORT
JniResult Xlog__logF(jobject self_,int64_t j,jobject string,jobject string1,jobject string2,int32_t i,int32_t i1,int64_t j1,int64_t j2,jobject string3) {
    load_env();
        load_class_global_ref(&_c_Xlog, "com/tencent/mars/xlog/Xlog");
    if (_c_Xlog == NULL) return (JniResult){.value = {.j = 0}, .exception = check_exception()};
    load_method(_c_Xlog,
      &_m_Xlog__logF, "logF", "(JLjava/lang/String;Ljava/lang/String;Ljava/lang/String;IIJJLjava/lang/String;)V");
    if (_m_Xlog__logF == NULL) return (JniResult){.value = {.j = 0}, .exception = check_exception()};
    (*jniEnv)->CallVoidMethod(jniEnv, self_, _m_Xlog__logF, j, string, string1, string2, i, i1, j1, j2, string3);
    return (JniResult){.value = {.j = 0}, .exception = check_exception()};
}

jmethodID _m_Xlog__appenderOpen = NULL;
FFI_PLUGIN_EXPORT
JniResult Xlog__appenderOpen(jobject self_,int32_t i,int32_t i1,jobject string,jobject string1,jobject string2,int32_t i2) {
    load_env();
        load_class_global_ref(&_c_Xlog, "com/tencent/mars/xlog/Xlog");
    if (_c_Xlog == NULL) return (JniResult){.value = {.j = 0}, .exception = check_exception()};
    load_method(_c_Xlog,
      &_m_Xlog__appenderOpen, "appenderOpen", "(IILjava/lang/String;Ljava/lang/String;Ljava/lang/String;I)V");
    if (_m_Xlog__appenderOpen == NULL) return (JniResult){.value = {.j = 0}, .exception = check_exception()};
    (*jniEnv)->CallVoidMethod(jniEnv, self_, _m_Xlog__appenderOpen, i, i1, string, string1, string2, i2);
    return (JniResult){.value = {.j = 0}, .exception = check_exception()};
}

jmethodID _m_Xlog__logWrite = NULL;
FFI_PLUGIN_EXPORT
JniResult Xlog__logWrite(jobject xLoggerInfo,jobject string) {
    load_env();
        load_class_global_ref(&_c_Xlog, "com/tencent/mars/xlog/Xlog");
    if (_c_Xlog == NULL) return (JniResult){.value = {.j = 0}, .exception = check_exception()};
    load_static_method(_c_Xlog,
      &_m_Xlog__logWrite, "logWrite", "(Lcom/tencent/mars/xlog/Xlog$XLoggerInfo;Ljava/lang/String;)V");
    if (_m_Xlog__logWrite == NULL) return (JniResult){.value = {.j = 0}, .exception = check_exception()};
    (*jniEnv)->CallStaticVoidMethod(jniEnv, _c_Xlog, _m_Xlog__logWrite, xLoggerInfo, string);
    return (JniResult){.value = {.j = 0}, .exception = check_exception()};
}

jmethodID _m_Xlog__logWrite2 = NULL;
FFI_PLUGIN_EXPORT
JniResult Xlog__logWrite2(int32_t i,jobject string,jobject string1,jobject string2,int32_t i1,int32_t i2,int64_t j,int64_t j1,jobject string3) {
    load_env();
        load_class_global_ref(&_c_Xlog, "com/tencent/mars/xlog/Xlog");
    if (_c_Xlog == NULL) return (JniResult){.value = {.j = 0}, .exception = check_exception()};
    load_static_method(_c_Xlog,
      &_m_Xlog__logWrite2, "logWrite2", "(ILjava/lang/String;Ljava/lang/String;Ljava/lang/String;IIJJLjava/lang/String;)V");
    if (_m_Xlog__logWrite2 == NULL) return (JniResult){.value = {.j = 0}, .exception = check_exception()};
    (*jniEnv)->CallStaticVoidMethod(jniEnv, _c_Xlog, _m_Xlog__logWrite2, i, string, string1, string2, i1, i2, j, j1, string3);
    return (JniResult){.value = {.j = 0}, .exception = check_exception()};
}

jmethodID _m_Xlog__logWrite21 = NULL;
FFI_PLUGIN_EXPORT
JniResult Xlog__logWrite21(int64_t j,int32_t i,jobject string,jobject string1,jobject string2,int32_t i1,int32_t i2,int64_t j1,int64_t j2,jobject string3) {
    load_env();
        load_class_global_ref(&_c_Xlog, "com/tencent/mars/xlog/Xlog");
    if (_c_Xlog == NULL) return (JniResult){.value = {.j = 0}, .exception = check_exception()};
    load_static_method(_c_Xlog,
      &_m_Xlog__logWrite21, "logWrite2", "(JILjava/lang/String;Ljava/lang/String;Ljava/lang/String;IIJJLjava/lang/String;)V");
    if (_m_Xlog__logWrite21 == NULL) return (JniResult){.value = {.j = 0}, .exception = check_exception()};
    (*jniEnv)->CallStaticVoidMethod(jniEnv, _c_Xlog, _m_Xlog__logWrite21, j, i, string, string1, string2, i1, i2, j1, j2, string3);
    return (JniResult){.value = {.j = 0}, .exception = check_exception()};
}

jmethodID _m_Xlog__getLogLevel = NULL;
FFI_PLUGIN_EXPORT
JniResult Xlog__getLogLevel(jobject self_,int64_t j) {
    load_env();
        load_class_global_ref(&_c_Xlog, "com/tencent/mars/xlog/Xlog");
    if (_c_Xlog == NULL) return (JniResult){.value = {.j = 0}, .exception = check_exception()};
    load_method(_c_Xlog,
      &_m_Xlog__getLogLevel, "getLogLevel", "(J)I");
    if (_m_Xlog__getLogLevel == NULL) return (JniResult){.value = {.j = 0}, .exception = check_exception()};
    int32_t _result = (*jniEnv)->CallIntMethod(jniEnv, self_, _m_Xlog__getLogLevel, j);
    return (JniResult){.value = {.i = _result}, .exception = check_exception()};
}

jmethodID _m_Xlog__setAppenderMode = NULL;
FFI_PLUGIN_EXPORT
JniResult Xlog__setAppenderMode(jobject self_,int64_t j,int32_t i) {
    load_env();
        load_class_global_ref(&_c_Xlog, "com/tencent/mars/xlog/Xlog");
    if (_c_Xlog == NULL) return (JniResult){.value = {.j = 0}, .exception = check_exception()};
    load_method(_c_Xlog,
      &_m_Xlog__setAppenderMode, "setAppenderMode", "(JI)V");
    if (_m_Xlog__setAppenderMode == NULL) return (JniResult){.value = {.j = 0}, .exception = check_exception()};
    (*jniEnv)->CallVoidMethod(jniEnv, self_, _m_Xlog__setAppenderMode, j, i);
    return (JniResult){.value = {.j = 0}, .exception = check_exception()};
}

jmethodID _m_Xlog__openLogInstance = NULL;
FFI_PLUGIN_EXPORT
JniResult Xlog__openLogInstance(jobject self_,int32_t i,int32_t i1,jobject string,jobject string1,jobject string2,int32_t i2) {
    load_env();
        load_class_global_ref(&_c_Xlog, "com/tencent/mars/xlog/Xlog");
    if (_c_Xlog == NULL) return (JniResult){.value = {.j = 0}, .exception = check_exception()};
    load_method(_c_Xlog,
      &_m_Xlog__openLogInstance, "openLogInstance", "(IILjava/lang/String;Ljava/lang/String;Ljava/lang/String;I)J");
    if (_m_Xlog__openLogInstance == NULL) return (JniResult){.value = {.j = 0}, .exception = check_exception()};
    int64_t _result = (*jniEnv)->CallLongMethod(jniEnv, self_, _m_Xlog__openLogInstance, i, i1, string, string1, string2, i2);
    return (JniResult){.value = {.j = _result}, .exception = check_exception()};
}

jmethodID _m_Xlog__getXlogInstance = NULL;
FFI_PLUGIN_EXPORT
JniResult Xlog__getXlogInstance(jobject self_,jobject string) {
    load_env();
        load_class_global_ref(&_c_Xlog, "com/tencent/mars/xlog/Xlog");
    if (_c_Xlog == NULL) return (JniResult){.value = {.j = 0}, .exception = check_exception()};
    load_method(_c_Xlog,
      &_m_Xlog__getXlogInstance, "getXlogInstance", "(Ljava/lang/String;)J");
    if (_m_Xlog__getXlogInstance == NULL) return (JniResult){.value = {.j = 0}, .exception = check_exception()};
    int64_t _result = (*jniEnv)->CallLongMethod(jniEnv, self_, _m_Xlog__getXlogInstance, string);
    return (JniResult){.value = {.j = _result}, .exception = check_exception()};
}

jmethodID _m_Xlog__releaseXlogInstance = NULL;
FFI_PLUGIN_EXPORT
JniResult Xlog__releaseXlogInstance(jobject self_,jobject string) {
    load_env();
        load_class_global_ref(&_c_Xlog, "com/tencent/mars/xlog/Xlog");
    if (_c_Xlog == NULL) return (JniResult){.value = {.j = 0}, .exception = check_exception()};
    load_method(_c_Xlog,
      &_m_Xlog__releaseXlogInstance, "releaseXlogInstance", "(Ljava/lang/String;)V");
    if (_m_Xlog__releaseXlogInstance == NULL) return (JniResult){.value = {.j = 0}, .exception = check_exception()};
    (*jniEnv)->CallVoidMethod(jniEnv, self_, _m_Xlog__releaseXlogInstance, string);
    return (JniResult){.value = {.j = 0}, .exception = check_exception()};
}

jmethodID _m_Xlog__newXlogInstance = NULL;
FFI_PLUGIN_EXPORT
JniResult Xlog__newXlogInstance(jobject self_,jobject xLogConfig) {
    load_env();
        load_class_global_ref(&_c_Xlog, "com/tencent/mars/xlog/Xlog");
    if (_c_Xlog == NULL) return (JniResult){.value = {.j = 0}, .exception = check_exception()};
    load_method(_c_Xlog,
      &_m_Xlog__newXlogInstance, "newXlogInstance", "(Lcom/tencent/mars/xlog/Xlog$XLogConfig;)J");
    if (_m_Xlog__newXlogInstance == NULL) return (JniResult){.value = {.j = 0}, .exception = check_exception()};
    int64_t _result = (*jniEnv)->CallLongMethod(jniEnv, self_, _m_Xlog__newXlogInstance, xLogConfig);
    return (JniResult){.value = {.j = _result}, .exception = check_exception()};
}

jmethodID _m_Xlog__setConsoleLogOpen = NULL;
FFI_PLUGIN_EXPORT
JniResult Xlog__setConsoleLogOpen(jobject self_,int64_t j,uint8_t z) {
    load_env();
        load_class_global_ref(&_c_Xlog, "com/tencent/mars/xlog/Xlog");
    if (_c_Xlog == NULL) return (JniResult){.value = {.j = 0}, .exception = check_exception()};
    load_method(_c_Xlog,
      &_m_Xlog__setConsoleLogOpen, "setConsoleLogOpen", "(JZ)V");
    if (_m_Xlog__setConsoleLogOpen == NULL) return (JniResult){.value = {.j = 0}, .exception = check_exception()};
    (*jniEnv)->CallVoidMethod(jniEnv, self_, _m_Xlog__setConsoleLogOpen, j, z);
    return (JniResult){.value = {.j = 0}, .exception = check_exception()};
}

jmethodID _m_Xlog__appenderClose = NULL;
FFI_PLUGIN_EXPORT
JniResult Xlog__appenderClose(jobject self_) {
    load_env();
        load_class_global_ref(&_c_Xlog, "com/tencent/mars/xlog/Xlog");
    if (_c_Xlog == NULL) return (JniResult){.value = {.j = 0}, .exception = check_exception()};
    load_method(_c_Xlog,
      &_m_Xlog__appenderClose, "appenderClose", "()V");
    if (_m_Xlog__appenderClose == NULL) return (JniResult){.value = {.j = 0}, .exception = check_exception()};
    (*jniEnv)->CallVoidMethod(jniEnv, self_, _m_Xlog__appenderClose);
    return (JniResult){.value = {.j = 0}, .exception = check_exception()};
}

jmethodID _m_Xlog__appenderFlush = NULL;
FFI_PLUGIN_EXPORT
JniResult Xlog__appenderFlush(jobject self_,int64_t j,uint8_t z) {
    load_env();
        load_class_global_ref(&_c_Xlog, "com/tencent/mars/xlog/Xlog");
    if (_c_Xlog == NULL) return (JniResult){.value = {.j = 0}, .exception = check_exception()};
    load_method(_c_Xlog,
      &_m_Xlog__appenderFlush, "appenderFlush", "(JZ)V");
    if (_m_Xlog__appenderFlush == NULL) return (JniResult){.value = {.j = 0}, .exception = check_exception()};
    (*jniEnv)->CallVoidMethod(jniEnv, self_, _m_Xlog__appenderFlush, j, z);
    return (JniResult){.value = {.j = 0}, .exception = check_exception()};
}

jmethodID _m_Xlog__setMaxFileSize = NULL;
FFI_PLUGIN_EXPORT
JniResult Xlog__setMaxFileSize(jobject self_,int64_t j,int64_t j1) {
    load_env();
        load_class_global_ref(&_c_Xlog, "com/tencent/mars/xlog/Xlog");
    if (_c_Xlog == NULL) return (JniResult){.value = {.j = 0}, .exception = check_exception()};
    load_method(_c_Xlog,
      &_m_Xlog__setMaxFileSize, "setMaxFileSize", "(JJ)V");
    if (_m_Xlog__setMaxFileSize == NULL) return (JniResult){.value = {.j = 0}, .exception = check_exception()};
    (*jniEnv)->CallVoidMethod(jniEnv, self_, _m_Xlog__setMaxFileSize, j, j1);
    return (JniResult){.value = {.j = 0}, .exception = check_exception()};
}

jmethodID _m_Xlog__setMaxAliveTime = NULL;
FFI_PLUGIN_EXPORT
JniResult Xlog__setMaxAliveTime(jobject self_,int64_t j,int64_t j1) {
    load_env();
        load_class_global_ref(&_c_Xlog, "com/tencent/mars/xlog/Xlog");
    if (_c_Xlog == NULL) return (JniResult){.value = {.j = 0}, .exception = check_exception()};
    load_method(_c_Xlog,
      &_m_Xlog__setMaxAliveTime, "setMaxAliveTime", "(JJ)V");
    if (_m_Xlog__setMaxAliveTime == NULL) return (JniResult){.value = {.j = 0}, .exception = check_exception()};
    (*jniEnv)->CallVoidMethod(jniEnv, self_, _m_Xlog__setMaxAliveTime, j, j1);
    return (JniResult){.value = {.j = 0}, .exception = check_exception()};
}

// com.tencent.mars.xlog.Log$LogImp
jclass _c_Log_LogImp = NULL;

jmethodID _m_Log_LogImp__logV = NULL;
FFI_PLUGIN_EXPORT
JniResult Log_LogImp__logV(jobject self_,int64_t j,jobject string,jobject string1,jobject string2,int32_t i,int32_t i1,int64_t j1,int64_t j2,jobject string3) {
    load_env();
        load_class_global_ref(&_c_Log_LogImp, "com/tencent/mars/xlog/Log$LogImp");
    if (_c_Log_LogImp == NULL) return (JniResult){.value = {.j = 0}, .exception = check_exception()};
    load_method(_c_Log_LogImp,
      &_m_Log_LogImp__logV, "logV", "(JLjava/lang/String;Ljava/lang/String;Ljava/lang/String;IIJJLjava/lang/String;)V");
    if (_m_Log_LogImp__logV == NULL) return (JniResult){.value = {.j = 0}, .exception = check_exception()};
    (*jniEnv)->CallVoidMethod(jniEnv, self_, _m_Log_LogImp__logV, j, string, string1, string2, i, i1, j1, j2, string3);
    return (JniResult){.value = {.j = 0}, .exception = check_exception()};
}

jmethodID _m_Log_LogImp__logI = NULL;
FFI_PLUGIN_EXPORT
JniResult Log_LogImp__logI(jobject self_,int64_t j,jobject string,jobject string1,jobject string2,int32_t i,int32_t i1,int64_t j1,int64_t j2,jobject string3) {
    load_env();
        load_class_global_ref(&_c_Log_LogImp, "com/tencent/mars/xlog/Log$LogImp");
    if (_c_Log_LogImp == NULL) return (JniResult){.value = {.j = 0}, .exception = check_exception()};
    load_method(_c_Log_LogImp,
      &_m_Log_LogImp__logI, "logI", "(JLjava/lang/String;Ljava/lang/String;Ljava/lang/String;IIJJLjava/lang/String;)V");
    if (_m_Log_LogImp__logI == NULL) return (JniResult){.value = {.j = 0}, .exception = check_exception()};
    (*jniEnv)->CallVoidMethod(jniEnv, self_, _m_Log_LogImp__logI, j, string, string1, string2, i, i1, j1, j2, string3);
    return (JniResult){.value = {.j = 0}, .exception = check_exception()};
}

jmethodID _m_Log_LogImp__logD = NULL;
FFI_PLUGIN_EXPORT
JniResult Log_LogImp__logD(jobject self_,int64_t j,jobject string,jobject string1,jobject string2,int32_t i,int32_t i1,int64_t j1,int64_t j2,jobject string3) {
    load_env();
        load_class_global_ref(&_c_Log_LogImp, "com/tencent/mars/xlog/Log$LogImp");
    if (_c_Log_LogImp == NULL) return (JniResult){.value = {.j = 0}, .exception = check_exception()};
    load_method(_c_Log_LogImp,
      &_m_Log_LogImp__logD, "logD", "(JLjava/lang/String;Ljava/lang/String;Ljava/lang/String;IIJJLjava/lang/String;)V");
    if (_m_Log_LogImp__logD == NULL) return (JniResult){.value = {.j = 0}, .exception = check_exception()};
    (*jniEnv)->CallVoidMethod(jniEnv, self_, _m_Log_LogImp__logD, j, string, string1, string2, i, i1, j1, j2, string3);
    return (JniResult){.value = {.j = 0}, .exception = check_exception()};
}

jmethodID _m_Log_LogImp__logW = NULL;
FFI_PLUGIN_EXPORT
JniResult Log_LogImp__logW(jobject self_,int64_t j,jobject string,jobject string1,jobject string2,int32_t i,int32_t i1,int64_t j1,int64_t j2,jobject string3) {
    load_env();
        load_class_global_ref(&_c_Log_LogImp, "com/tencent/mars/xlog/Log$LogImp");
    if (_c_Log_LogImp == NULL) return (JniResult){.value = {.j = 0}, .exception = check_exception()};
    load_method(_c_Log_LogImp,
      &_m_Log_LogImp__logW, "logW", "(JLjava/lang/String;Ljava/lang/String;Ljava/lang/String;IIJJLjava/lang/String;)V");
    if (_m_Log_LogImp__logW == NULL) return (JniResult){.value = {.j = 0}, .exception = check_exception()};
    (*jniEnv)->CallVoidMethod(jniEnv, self_, _m_Log_LogImp__logW, j, string, string1, string2, i, i1, j1, j2, string3);
    return (JniResult){.value = {.j = 0}, .exception = check_exception()};
}

jmethodID _m_Log_LogImp__logE = NULL;
FFI_PLUGIN_EXPORT
JniResult Log_LogImp__logE(jobject self_,int64_t j,jobject string,jobject string1,jobject string2,int32_t i,int32_t i1,int64_t j1,int64_t j2,jobject string3) {
    load_env();
        load_class_global_ref(&_c_Log_LogImp, "com/tencent/mars/xlog/Log$LogImp");
    if (_c_Log_LogImp == NULL) return (JniResult){.value = {.j = 0}, .exception = check_exception()};
    load_method(_c_Log_LogImp,
      &_m_Log_LogImp__logE, "logE", "(JLjava/lang/String;Ljava/lang/String;Ljava/lang/String;IIJJLjava/lang/String;)V");
    if (_m_Log_LogImp__logE == NULL) return (JniResult){.value = {.j = 0}, .exception = check_exception()};
    (*jniEnv)->CallVoidMethod(jniEnv, self_, _m_Log_LogImp__logE, j, string, string1, string2, i, i1, j1, j2, string3);
    return (JniResult){.value = {.j = 0}, .exception = check_exception()};
}

jmethodID _m_Log_LogImp__logF = NULL;
FFI_PLUGIN_EXPORT
JniResult Log_LogImp__logF(jobject self_,int64_t j,jobject string,jobject string1,jobject string2,int32_t i,int32_t i1,int64_t j1,int64_t j2,jobject string3) {
    load_env();
        load_class_global_ref(&_c_Log_LogImp, "com/tencent/mars/xlog/Log$LogImp");
    if (_c_Log_LogImp == NULL) return (JniResult){.value = {.j = 0}, .exception = check_exception()};
    load_method(_c_Log_LogImp,
      &_m_Log_LogImp__logF, "logF", "(JLjava/lang/String;Ljava/lang/String;Ljava/lang/String;IIJJLjava/lang/String;)V");
    if (_m_Log_LogImp__logF == NULL) return (JniResult){.value = {.j = 0}, .exception = check_exception()};
    (*jniEnv)->CallVoidMethod(jniEnv, self_, _m_Log_LogImp__logF, j, string, string1, string2, i, i1, j1, j2, string3);
    return (JniResult){.value = {.j = 0}, .exception = check_exception()};
}

jmethodID _m_Log_LogImp__getLogLevel = NULL;
FFI_PLUGIN_EXPORT
JniResult Log_LogImp__getLogLevel(jobject self_,int64_t j) {
    load_env();
        load_class_global_ref(&_c_Log_LogImp, "com/tencent/mars/xlog/Log$LogImp");
    if (_c_Log_LogImp == NULL) return (JniResult){.value = {.j = 0}, .exception = check_exception()};
    load_method(_c_Log_LogImp,
      &_m_Log_LogImp__getLogLevel, "getLogLevel", "(J)I");
    if (_m_Log_LogImp__getLogLevel == NULL) return (JniResult){.value = {.j = 0}, .exception = check_exception()};
    int32_t _result = (*jniEnv)->CallIntMethod(jniEnv, self_, _m_Log_LogImp__getLogLevel, j);
    return (JniResult){.value = {.i = _result}, .exception = check_exception()};
}

jmethodID _m_Log_LogImp__setAppenderMode = NULL;
FFI_PLUGIN_EXPORT
JniResult Log_LogImp__setAppenderMode(jobject self_,int64_t j,int32_t i) {
    load_env();
        load_class_global_ref(&_c_Log_LogImp, "com/tencent/mars/xlog/Log$LogImp");
    if (_c_Log_LogImp == NULL) return (JniResult){.value = {.j = 0}, .exception = check_exception()};
    load_method(_c_Log_LogImp,
      &_m_Log_LogImp__setAppenderMode, "setAppenderMode", "(JI)V");
    if (_m_Log_LogImp__setAppenderMode == NULL) return (JniResult){.value = {.j = 0}, .exception = check_exception()};
    (*jniEnv)->CallVoidMethod(jniEnv, self_, _m_Log_LogImp__setAppenderMode, j, i);
    return (JniResult){.value = {.j = 0}, .exception = check_exception()};
}

jmethodID _m_Log_LogImp__openLogInstance = NULL;
FFI_PLUGIN_EXPORT
JniResult Log_LogImp__openLogInstance(jobject self_,int32_t i,int32_t i1,jobject string,jobject string1,jobject string2,int32_t i2) {
    load_env();
        load_class_global_ref(&_c_Log_LogImp, "com/tencent/mars/xlog/Log$LogImp");
    if (_c_Log_LogImp == NULL) return (JniResult){.value = {.j = 0}, .exception = check_exception()};
    load_method(_c_Log_LogImp,
      &_m_Log_LogImp__openLogInstance, "openLogInstance", "(IILjava/lang/String;Ljava/lang/String;Ljava/lang/String;I)J");
    if (_m_Log_LogImp__openLogInstance == NULL) return (JniResult){.value = {.j = 0}, .exception = check_exception()};
    int64_t _result = (*jniEnv)->CallLongMethod(jniEnv, self_, _m_Log_LogImp__openLogInstance, i, i1, string, string1, string2, i2);
    return (JniResult){.value = {.j = _result}, .exception = check_exception()};
}

jmethodID _m_Log_LogImp__getXlogInstance = NULL;
FFI_PLUGIN_EXPORT
JniResult Log_LogImp__getXlogInstance(jobject self_,jobject string) {
    load_env();
        load_class_global_ref(&_c_Log_LogImp, "com/tencent/mars/xlog/Log$LogImp");
    if (_c_Log_LogImp == NULL) return (JniResult){.value = {.j = 0}, .exception = check_exception()};
    load_method(_c_Log_LogImp,
      &_m_Log_LogImp__getXlogInstance, "getXlogInstance", "(Ljava/lang/String;)J");
    if (_m_Log_LogImp__getXlogInstance == NULL) return (JniResult){.value = {.j = 0}, .exception = check_exception()};
    int64_t _result = (*jniEnv)->CallLongMethod(jniEnv, self_, _m_Log_LogImp__getXlogInstance, string);
    return (JniResult){.value = {.j = _result}, .exception = check_exception()};
}

jmethodID _m_Log_LogImp__releaseXlogInstance = NULL;
FFI_PLUGIN_EXPORT
JniResult Log_LogImp__releaseXlogInstance(jobject self_,jobject string) {
    load_env();
        load_class_global_ref(&_c_Log_LogImp, "com/tencent/mars/xlog/Log$LogImp");
    if (_c_Log_LogImp == NULL) return (JniResult){.value = {.j = 0}, .exception = check_exception()};
    load_method(_c_Log_LogImp,
      &_m_Log_LogImp__releaseXlogInstance, "releaseXlogInstance", "(Ljava/lang/String;)V");
    if (_m_Log_LogImp__releaseXlogInstance == NULL) return (JniResult){.value = {.j = 0}, .exception = check_exception()};
    (*jniEnv)->CallVoidMethod(jniEnv, self_, _m_Log_LogImp__releaseXlogInstance, string);
    return (JniResult){.value = {.j = 0}, .exception = check_exception()};
}

jmethodID _m_Log_LogImp__appenderOpen = NULL;
FFI_PLUGIN_EXPORT
JniResult Log_LogImp__appenderOpen(jobject self_,int32_t i,int32_t i1,jobject string,jobject string1,jobject string2,int32_t i2) {
    load_env();
        load_class_global_ref(&_c_Log_LogImp, "com/tencent/mars/xlog/Log$LogImp");
    if (_c_Log_LogImp == NULL) return (JniResult){.value = {.j = 0}, .exception = check_exception()};
    load_method(_c_Log_LogImp,
      &_m_Log_LogImp__appenderOpen, "appenderOpen", "(IILjava/lang/String;Ljava/lang/String;Ljava/lang/String;I)V");
    if (_m_Log_LogImp__appenderOpen == NULL) return (JniResult){.value = {.j = 0}, .exception = check_exception()};
    (*jniEnv)->CallVoidMethod(jniEnv, self_, _m_Log_LogImp__appenderOpen, i, i1, string, string1, string2, i2);
    return (JniResult){.value = {.j = 0}, .exception = check_exception()};
}

jmethodID _m_Log_LogImp__appenderClose = NULL;
FFI_PLUGIN_EXPORT
JniResult Log_LogImp__appenderClose(jobject self_) {
    load_env();
        load_class_global_ref(&_c_Log_LogImp, "com/tencent/mars/xlog/Log$LogImp");
    if (_c_Log_LogImp == NULL) return (JniResult){.value = {.j = 0}, .exception = check_exception()};
    load_method(_c_Log_LogImp,
      &_m_Log_LogImp__appenderClose, "appenderClose", "()V");
    if (_m_Log_LogImp__appenderClose == NULL) return (JniResult){.value = {.j = 0}, .exception = check_exception()};
    (*jniEnv)->CallVoidMethod(jniEnv, self_, _m_Log_LogImp__appenderClose);
    return (JniResult){.value = {.j = 0}, .exception = check_exception()};
}

jmethodID _m_Log_LogImp__appenderFlush = NULL;
FFI_PLUGIN_EXPORT
JniResult Log_LogImp__appenderFlush(jobject self_,int64_t j,uint8_t z) {
    load_env();
        load_class_global_ref(&_c_Log_LogImp, "com/tencent/mars/xlog/Log$LogImp");
    if (_c_Log_LogImp == NULL) return (JniResult){.value = {.j = 0}, .exception = check_exception()};
    load_method(_c_Log_LogImp,
      &_m_Log_LogImp__appenderFlush, "appenderFlush", "(JZ)V");
    if (_m_Log_LogImp__appenderFlush == NULL) return (JniResult){.value = {.j = 0}, .exception = check_exception()};
    (*jniEnv)->CallVoidMethod(jniEnv, self_, _m_Log_LogImp__appenderFlush, j, z);
    return (JniResult){.value = {.j = 0}, .exception = check_exception()};
}

jmethodID _m_Log_LogImp__setConsoleLogOpen = NULL;
FFI_PLUGIN_EXPORT
JniResult Log_LogImp__setConsoleLogOpen(jobject self_,int64_t j,uint8_t z) {
    load_env();
        load_class_global_ref(&_c_Log_LogImp, "com/tencent/mars/xlog/Log$LogImp");
    if (_c_Log_LogImp == NULL) return (JniResult){.value = {.j = 0}, .exception = check_exception()};
    load_method(_c_Log_LogImp,
      &_m_Log_LogImp__setConsoleLogOpen, "setConsoleLogOpen", "(JZ)V");
    if (_m_Log_LogImp__setConsoleLogOpen == NULL) return (JniResult){.value = {.j = 0}, .exception = check_exception()};
    (*jniEnv)->CallVoidMethod(jniEnv, self_, _m_Log_LogImp__setConsoleLogOpen, j, z);
    return (JniResult){.value = {.j = 0}, .exception = check_exception()};
}

jmethodID _m_Log_LogImp__setMaxFileSize = NULL;
FFI_PLUGIN_EXPORT
JniResult Log_LogImp__setMaxFileSize(jobject self_,int64_t j,int64_t j1) {
    load_env();
        load_class_global_ref(&_c_Log_LogImp, "com/tencent/mars/xlog/Log$LogImp");
    if (_c_Log_LogImp == NULL) return (JniResult){.value = {.j = 0}, .exception = check_exception()};
    load_method(_c_Log_LogImp,
      &_m_Log_LogImp__setMaxFileSize, "setMaxFileSize", "(JJ)V");
    if (_m_Log_LogImp__setMaxFileSize == NULL) return (JniResult){.value = {.j = 0}, .exception = check_exception()};
    (*jniEnv)->CallVoidMethod(jniEnv, self_, _m_Log_LogImp__setMaxFileSize, j, j1);
    return (JniResult){.value = {.j = 0}, .exception = check_exception()};
}

jmethodID _m_Log_LogImp__setMaxAliveTime = NULL;
FFI_PLUGIN_EXPORT
JniResult Log_LogImp__setMaxAliveTime(jobject self_,int64_t j,int64_t j1) {
    load_env();
        load_class_global_ref(&_c_Log_LogImp, "com/tencent/mars/xlog/Log$LogImp");
    if (_c_Log_LogImp == NULL) return (JniResult){.value = {.j = 0}, .exception = check_exception()};
    load_method(_c_Log_LogImp,
      &_m_Log_LogImp__setMaxAliveTime, "setMaxAliveTime", "(JJ)V");
    if (_m_Log_LogImp__setMaxAliveTime == NULL) return (JniResult){.value = {.j = 0}, .exception = check_exception()};
    (*jniEnv)->CallVoidMethod(jniEnv, self_, _m_Log_LogImp__setMaxAliveTime, j, j1);
    return (JniResult){.value = {.j = 0}, .exception = check_exception()};
}

// com.tencent.mars.xlog.Log$LogInstance
jclass _c_Log_LogInstance = NULL;

jmethodID _m_Log_LogInstance__f = NULL;
FFI_PLUGIN_EXPORT
JniResult Log_LogInstance__f(jobject self_,jobject string,jobject string1,jobject objects) {
    load_env();
        load_class_global_ref(&_c_Log_LogInstance, "com/tencent/mars/xlog/Log$LogInstance");
    if (_c_Log_LogInstance == NULL) return (JniResult){.value = {.j = 0}, .exception = check_exception()};
    load_method(_c_Log_LogInstance,
      &_m_Log_LogInstance__f, "f", "(Ljava/lang/String;Ljava/lang/String;[Ljava/lang/Object;)V");
    if (_m_Log_LogInstance__f == NULL) return (JniResult){.value = {.j = 0}, .exception = check_exception()};
    (*jniEnv)->CallVoidMethod(jniEnv, self_, _m_Log_LogInstance__f, string, string1, objects);
    return (JniResult){.value = {.j = 0}, .exception = check_exception()};
}

jmethodID _m_Log_LogInstance__e = NULL;
FFI_PLUGIN_EXPORT
JniResult Log_LogInstance__e(jobject self_,jobject string,jobject string1,jobject objects) {
    load_env();
        load_class_global_ref(&_c_Log_LogInstance, "com/tencent/mars/xlog/Log$LogInstance");
    if (_c_Log_LogInstance == NULL) return (JniResult){.value = {.j = 0}, .exception = check_exception()};
    load_method(_c_Log_LogInstance,
      &_m_Log_LogInstance__e, "e", "(Ljava/lang/String;Ljava/lang/String;[Ljava/lang/Object;)V");
    if (_m_Log_LogInstance__e == NULL) return (JniResult){.value = {.j = 0}, .exception = check_exception()};
    (*jniEnv)->CallVoidMethod(jniEnv, self_, _m_Log_LogInstance__e, string, string1, objects);
    return (JniResult){.value = {.j = 0}, .exception = check_exception()};
}

jmethodID _m_Log_LogInstance__w = NULL;
FFI_PLUGIN_EXPORT
JniResult Log_LogInstance__w(jobject self_,jobject string,jobject string1,jobject objects) {
    load_env();
        load_class_global_ref(&_c_Log_LogInstance, "com/tencent/mars/xlog/Log$LogInstance");
    if (_c_Log_LogInstance == NULL) return (JniResult){.value = {.j = 0}, .exception = check_exception()};
    load_method(_c_Log_LogInstance,
      &_m_Log_LogInstance__w, "w", "(Ljava/lang/String;Ljava/lang/String;[Ljava/lang/Object;)V");
    if (_m_Log_LogInstance__w == NULL) return (JniResult){.value = {.j = 0}, .exception = check_exception()};
    (*jniEnv)->CallVoidMethod(jniEnv, self_, _m_Log_LogInstance__w, string, string1, objects);
    return (JniResult){.value = {.j = 0}, .exception = check_exception()};
}

jmethodID _m_Log_LogInstance__i = NULL;
FFI_PLUGIN_EXPORT
JniResult Log_LogInstance__i(jobject self_,jobject string,jobject string1,jobject objects) {
    load_env();
        load_class_global_ref(&_c_Log_LogInstance, "com/tencent/mars/xlog/Log$LogInstance");
    if (_c_Log_LogInstance == NULL) return (JniResult){.value = {.j = 0}, .exception = check_exception()};
    load_method(_c_Log_LogInstance,
      &_m_Log_LogInstance__i, "i", "(Ljava/lang/String;Ljava/lang/String;[Ljava/lang/Object;)V");
    if (_m_Log_LogInstance__i == NULL) return (JniResult){.value = {.j = 0}, .exception = check_exception()};
    (*jniEnv)->CallVoidMethod(jniEnv, self_, _m_Log_LogInstance__i, string, string1, objects);
    return (JniResult){.value = {.j = 0}, .exception = check_exception()};
}

jmethodID _m_Log_LogInstance__d = NULL;
FFI_PLUGIN_EXPORT
JniResult Log_LogInstance__d(jobject self_,jobject string,jobject string1,jobject objects) {
    load_env();
        load_class_global_ref(&_c_Log_LogInstance, "com/tencent/mars/xlog/Log$LogInstance");
    if (_c_Log_LogInstance == NULL) return (JniResult){.value = {.j = 0}, .exception = check_exception()};
    load_method(_c_Log_LogInstance,
      &_m_Log_LogInstance__d, "d", "(Ljava/lang/String;Ljava/lang/String;[Ljava/lang/Object;)V");
    if (_m_Log_LogInstance__d == NULL) return (JniResult){.value = {.j = 0}, .exception = check_exception()};
    (*jniEnv)->CallVoidMethod(jniEnv, self_, _m_Log_LogInstance__d, string, string1, objects);
    return (JniResult){.value = {.j = 0}, .exception = check_exception()};
}

jmethodID _m_Log_LogInstance__v = NULL;
FFI_PLUGIN_EXPORT
JniResult Log_LogInstance__v(jobject self_,jobject string,jobject string1,jobject objects) {
    load_env();
        load_class_global_ref(&_c_Log_LogInstance, "com/tencent/mars/xlog/Log$LogInstance");
    if (_c_Log_LogInstance == NULL) return (JniResult){.value = {.j = 0}, .exception = check_exception()};
    load_method(_c_Log_LogInstance,
      &_m_Log_LogInstance__v, "v", "(Ljava/lang/String;Ljava/lang/String;[Ljava/lang/Object;)V");
    if (_m_Log_LogInstance__v == NULL) return (JniResult){.value = {.j = 0}, .exception = check_exception()};
    (*jniEnv)->CallVoidMethod(jniEnv, self_, _m_Log_LogInstance__v, string, string1, objects);
    return (JniResult){.value = {.j = 0}, .exception = check_exception()};
}

jmethodID _m_Log_LogInstance__printErrStackTrace = NULL;
FFI_PLUGIN_EXPORT
JniResult Log_LogInstance__printErrStackTrace(jobject self_,jobject string,jobject throwable,jobject string1,jobject objects) {
    load_env();
        load_class_global_ref(&_c_Log_LogInstance, "com/tencent/mars/xlog/Log$LogInstance");
    if (_c_Log_LogInstance == NULL) return (JniResult){.value = {.j = 0}, .exception = check_exception()};
    load_method(_c_Log_LogInstance,
      &_m_Log_LogInstance__printErrStackTrace, "printErrStackTrace", "(Ljava/lang/String;Ljava/lang/Throwable;Ljava/lang/String;[Ljava/lang/Object;)V");
    if (_m_Log_LogInstance__printErrStackTrace == NULL) return (JniResult){.value = {.j = 0}, .exception = check_exception()};
    (*jniEnv)->CallVoidMethod(jniEnv, self_, _m_Log_LogInstance__printErrStackTrace, string, throwable, string1, objects);
    return (JniResult){.value = {.j = 0}, .exception = check_exception()};
}

jmethodID _m_Log_LogInstance__appenderFlush = NULL;
FFI_PLUGIN_EXPORT
JniResult Log_LogInstance__appenderFlush(jobject self_) {
    load_env();
        load_class_global_ref(&_c_Log_LogInstance, "com/tencent/mars/xlog/Log$LogInstance");
    if (_c_Log_LogInstance == NULL) return (JniResult){.value = {.j = 0}, .exception = check_exception()};
    load_method(_c_Log_LogInstance,
      &_m_Log_LogInstance__appenderFlush, "appenderFlush", "()V");
    if (_m_Log_LogInstance__appenderFlush == NULL) return (JniResult){.value = {.j = 0}, .exception = check_exception()};
    (*jniEnv)->CallVoidMethod(jniEnv, self_, _m_Log_LogInstance__appenderFlush);
    return (JniResult){.value = {.j = 0}, .exception = check_exception()};
}

jmethodID _m_Log_LogInstance__appenderFlushSync = NULL;
FFI_PLUGIN_EXPORT
JniResult Log_LogInstance__appenderFlushSync(jobject self_) {
    load_env();
        load_class_global_ref(&_c_Log_LogInstance, "com/tencent/mars/xlog/Log$LogInstance");
    if (_c_Log_LogInstance == NULL) return (JniResult){.value = {.j = 0}, .exception = check_exception()};
    load_method(_c_Log_LogInstance,
      &_m_Log_LogInstance__appenderFlushSync, "appenderFlushSync", "()V");
    if (_m_Log_LogInstance__appenderFlushSync == NULL) return (JniResult){.value = {.j = 0}, .exception = check_exception()};
    (*jniEnv)->CallVoidMethod(jniEnv, self_, _m_Log_LogInstance__appenderFlushSync);
    return (JniResult){.value = {.j = 0}, .exception = check_exception()};
}

jmethodID _m_Log_LogInstance__getLogLevel = NULL;
FFI_PLUGIN_EXPORT
JniResult Log_LogInstance__getLogLevel(jobject self_) {
    load_env();
        load_class_global_ref(&_c_Log_LogInstance, "com/tencent/mars/xlog/Log$LogInstance");
    if (_c_Log_LogInstance == NULL) return (JniResult){.value = {.j = 0}, .exception = check_exception()};
    load_method(_c_Log_LogInstance,
      &_m_Log_LogInstance__getLogLevel, "getLogLevel", "()I");
    if (_m_Log_LogInstance__getLogLevel == NULL) return (JniResult){.value = {.j = 0}, .exception = check_exception()};
    int32_t _result = (*jniEnv)->CallIntMethod(jniEnv, self_, _m_Log_LogInstance__getLogLevel);
    return (JniResult){.value = {.i = _result}, .exception = check_exception()};
}

jmethodID _m_Log_LogInstance__setConsoleLogOpen = NULL;
FFI_PLUGIN_EXPORT
JniResult Log_LogInstance__setConsoleLogOpen(jobject self_,uint8_t z) {
    load_env();
        load_class_global_ref(&_c_Log_LogInstance, "com/tencent/mars/xlog/Log$LogInstance");
    if (_c_Log_LogInstance == NULL) return (JniResult){.value = {.j = 0}, .exception = check_exception()};
    load_method(_c_Log_LogInstance,
      &_m_Log_LogInstance__setConsoleLogOpen, "setConsoleLogOpen", "(Z)V");
    if (_m_Log_LogInstance__setConsoleLogOpen == NULL) return (JniResult){.value = {.j = 0}, .exception = check_exception()};
    (*jniEnv)->CallVoidMethod(jniEnv, self_, _m_Log_LogInstance__setConsoleLogOpen, z);
    return (JniResult){.value = {.j = 0}, .exception = check_exception()};
}

// com.tencent.mars.xlog.Log
jclass _c_Log = NULL;

jmethodID _m_Log__new0 = NULL;
FFI_PLUGIN_EXPORT
JniResult Log__new0() {
    load_env();
        load_class_global_ref(&_c_Log, "com/tencent/mars/xlog/Log");
    if (_c_Log == NULL) return (JniResult){.value = {.j = 0}, .exception = check_exception()};
    load_method(_c_Log,
      &_m_Log__new0, "<init>", "()V");
    if (_m_Log__new0 == NULL) return (JniResult){.value = {.j = 0}, .exception = check_exception()};
    jobject _result = (*jniEnv)->NewObject(jniEnv, _c_Log, _m_Log__new0);
    return to_global_ref_result(_result);
}

jmethodID _m_Log__setLogImp = NULL;
FFI_PLUGIN_EXPORT
JniResult Log__setLogImp(jobject logImp) {
    load_env();
        load_class_global_ref(&_c_Log, "com/tencent/mars/xlog/Log");
    if (_c_Log == NULL) return (JniResult){.value = {.j = 0}, .exception = check_exception()};
    load_static_method(_c_Log,
      &_m_Log__setLogImp, "setLogImp", "(Lcom/tencent/mars/xlog/Log$LogImp;)V");
    if (_m_Log__setLogImp == NULL) return (JniResult){.value = {.j = 0}, .exception = check_exception()};
    (*jniEnv)->CallStaticVoidMethod(jniEnv, _c_Log, _m_Log__setLogImp, logImp);
    return (JniResult){.value = {.j = 0}, .exception = check_exception()};
}

jmethodID _m_Log__getImpl = NULL;
FFI_PLUGIN_EXPORT
JniResult Log__getImpl() {
    load_env();
        load_class_global_ref(&_c_Log, "com/tencent/mars/xlog/Log");
    if (_c_Log == NULL) return (JniResult){.value = {.j = 0}, .exception = check_exception()};
    load_static_method(_c_Log,
      &_m_Log__getImpl, "getImpl", "()Lcom/tencent/mars/xlog/Log$LogImp;");
    if (_m_Log__getImpl == NULL) return (JniResult){.value = {.j = 0}, .exception = check_exception()};
    jobject _result = (*jniEnv)->CallStaticObjectMethod(jniEnv, _c_Log, _m_Log__getImpl);
    return to_global_ref_result(_result);
}

jmethodID _m_Log__appenderOpen = NULL;
FFI_PLUGIN_EXPORT
JniResult Log__appenderOpen(int32_t i,int32_t i1,jobject string,jobject string1,jobject string2,int32_t i2) {
    load_env();
        load_class_global_ref(&_c_Log, "com/tencent/mars/xlog/Log");
    if (_c_Log == NULL) return (JniResult){.value = {.j = 0}, .exception = check_exception()};
    load_static_method(_c_Log,
      &_m_Log__appenderOpen, "appenderOpen", "(IILjava/lang/String;Ljava/lang/String;Ljava/lang/String;I)V");
    if (_m_Log__appenderOpen == NULL) return (JniResult){.value = {.j = 0}, .exception = check_exception()};
    (*jniEnv)->CallStaticVoidMethod(jniEnv, _c_Log, _m_Log__appenderOpen, i, i1, string, string1, string2, i2);
    return (JniResult){.value = {.j = 0}, .exception = check_exception()};
}

jmethodID _m_Log__appenderClose = NULL;
FFI_PLUGIN_EXPORT
JniResult Log__appenderClose() {
    load_env();
        load_class_global_ref(&_c_Log, "com/tencent/mars/xlog/Log");
    if (_c_Log == NULL) return (JniResult){.value = {.j = 0}, .exception = check_exception()};
    load_static_method(_c_Log,
      &_m_Log__appenderClose, "appenderClose", "()V");
    if (_m_Log__appenderClose == NULL) return (JniResult){.value = {.j = 0}, .exception = check_exception()};
    (*jniEnv)->CallStaticVoidMethod(jniEnv, _c_Log, _m_Log__appenderClose);
    return (JniResult){.value = {.j = 0}, .exception = check_exception()};
}

jmethodID _m_Log__appenderFlush = NULL;
FFI_PLUGIN_EXPORT
JniResult Log__appenderFlush() {
    load_env();
        load_class_global_ref(&_c_Log, "com/tencent/mars/xlog/Log");
    if (_c_Log == NULL) return (JniResult){.value = {.j = 0}, .exception = check_exception()};
    load_static_method(_c_Log,
      &_m_Log__appenderFlush, "appenderFlush", "()V");
    if (_m_Log__appenderFlush == NULL) return (JniResult){.value = {.j = 0}, .exception = check_exception()};
    (*jniEnv)->CallStaticVoidMethod(jniEnv, _c_Log, _m_Log__appenderFlush);
    return (JniResult){.value = {.j = 0}, .exception = check_exception()};
}

jmethodID _m_Log__appenderFlushSync = NULL;
FFI_PLUGIN_EXPORT
JniResult Log__appenderFlushSync(uint8_t z) {
    load_env();
        load_class_global_ref(&_c_Log, "com/tencent/mars/xlog/Log");
    if (_c_Log == NULL) return (JniResult){.value = {.j = 0}, .exception = check_exception()};
    load_static_method(_c_Log,
      &_m_Log__appenderFlushSync, "appenderFlushSync", "(Z)V");
    if (_m_Log__appenderFlushSync == NULL) return (JniResult){.value = {.j = 0}, .exception = check_exception()};
    (*jniEnv)->CallStaticVoidMethod(jniEnv, _c_Log, _m_Log__appenderFlushSync, z);
    return (JniResult){.value = {.j = 0}, .exception = check_exception()};
}

jmethodID _m_Log__getLogLevel = NULL;
FFI_PLUGIN_EXPORT
JniResult Log__getLogLevel() {
    load_env();
        load_class_global_ref(&_c_Log, "com/tencent/mars/xlog/Log");
    if (_c_Log == NULL) return (JniResult){.value = {.j = 0}, .exception = check_exception()};
    load_static_method(_c_Log,
      &_m_Log__getLogLevel, "getLogLevel", "()I");
    if (_m_Log__getLogLevel == NULL) return (JniResult){.value = {.j = 0}, .exception = check_exception()};
    int32_t _result = (*jniEnv)->CallStaticIntMethod(jniEnv, _c_Log, _m_Log__getLogLevel);
    return (JniResult){.value = {.i = _result}, .exception = check_exception()};
}

jmethodID _m_Log__setLevel = NULL;
FFI_PLUGIN_EXPORT
JniResult Log__setLevel(int32_t i,uint8_t z) {
    load_env();
        load_class_global_ref(&_c_Log, "com/tencent/mars/xlog/Log");
    if (_c_Log == NULL) return (JniResult){.value = {.j = 0}, .exception = check_exception()};
    load_static_method(_c_Log,
      &_m_Log__setLevel, "setLevel", "(IZ)V");
    if (_m_Log__setLevel == NULL) return (JniResult){.value = {.j = 0}, .exception = check_exception()};
    (*jniEnv)->CallStaticVoidMethod(jniEnv, _c_Log, _m_Log__setLevel, i, z);
    return (JniResult){.value = {.j = 0}, .exception = check_exception()};
}

jmethodID _m_Log__setConsoleLogOpen = NULL;
FFI_PLUGIN_EXPORT
JniResult Log__setConsoleLogOpen(uint8_t z) {
    load_env();
        load_class_global_ref(&_c_Log, "com/tencent/mars/xlog/Log");
    if (_c_Log == NULL) return (JniResult){.value = {.j = 0}, .exception = check_exception()};
    load_static_method(_c_Log,
      &_m_Log__setConsoleLogOpen, "setConsoleLogOpen", "(Z)V");
    if (_m_Log__setConsoleLogOpen == NULL) return (JniResult){.value = {.j = 0}, .exception = check_exception()};
    (*jniEnv)->CallStaticVoidMethod(jniEnv, _c_Log, _m_Log__setConsoleLogOpen, z);
    return (JniResult){.value = {.j = 0}, .exception = check_exception()};
}

jmethodID _m_Log__f = NULL;
FFI_PLUGIN_EXPORT
JniResult Log__f(jobject string,jobject string1) {
    load_env();
        load_class_global_ref(&_c_Log, "com/tencent/mars/xlog/Log");
    if (_c_Log == NULL) return (JniResult){.value = {.j = 0}, .exception = check_exception()};
    load_static_method(_c_Log,
      &_m_Log__f, "f", "(Ljava/lang/String;Ljava/lang/String;)V");
    if (_m_Log__f == NULL) return (JniResult){.value = {.j = 0}, .exception = check_exception()};
    (*jniEnv)->CallStaticVoidMethod(jniEnv, _c_Log, _m_Log__f, string, string1);
    return (JniResult){.value = {.j = 0}, .exception = check_exception()};
}

jmethodID _m_Log__e = NULL;
FFI_PLUGIN_EXPORT
JniResult Log__e(jobject string,jobject string1) {
    load_env();
        load_class_global_ref(&_c_Log, "com/tencent/mars/xlog/Log");
    if (_c_Log == NULL) return (JniResult){.value = {.j = 0}, .exception = check_exception()};
    load_static_method(_c_Log,
      &_m_Log__e, "e", "(Ljava/lang/String;Ljava/lang/String;)V");
    if (_m_Log__e == NULL) return (JniResult){.value = {.j = 0}, .exception = check_exception()};
    (*jniEnv)->CallStaticVoidMethod(jniEnv, _c_Log, _m_Log__e, string, string1);
    return (JniResult){.value = {.j = 0}, .exception = check_exception()};
}

jmethodID _m_Log__w = NULL;
FFI_PLUGIN_EXPORT
JniResult Log__w(jobject string,jobject string1) {
    load_env();
        load_class_global_ref(&_c_Log, "com/tencent/mars/xlog/Log");
    if (_c_Log == NULL) return (JniResult){.value = {.j = 0}, .exception = check_exception()};
    load_static_method(_c_Log,
      &_m_Log__w, "w", "(Ljava/lang/String;Ljava/lang/String;)V");
    if (_m_Log__w == NULL) return (JniResult){.value = {.j = 0}, .exception = check_exception()};
    (*jniEnv)->CallStaticVoidMethod(jniEnv, _c_Log, _m_Log__w, string, string1);
    return (JniResult){.value = {.j = 0}, .exception = check_exception()};
}

jmethodID _m_Log__i = NULL;
FFI_PLUGIN_EXPORT
JniResult Log__i(jobject string,jobject string1) {
    load_env();
        load_class_global_ref(&_c_Log, "com/tencent/mars/xlog/Log");
    if (_c_Log == NULL) return (JniResult){.value = {.j = 0}, .exception = check_exception()};
    load_static_method(_c_Log,
      &_m_Log__i, "i", "(Ljava/lang/String;Ljava/lang/String;)V");
    if (_m_Log__i == NULL) return (JniResult){.value = {.j = 0}, .exception = check_exception()};
    (*jniEnv)->CallStaticVoidMethod(jniEnv, _c_Log, _m_Log__i, string, string1);
    return (JniResult){.value = {.j = 0}, .exception = check_exception()};
}

jmethodID _m_Log__d = NULL;
FFI_PLUGIN_EXPORT
JniResult Log__d(jobject string,jobject string1) {
    load_env();
        load_class_global_ref(&_c_Log, "com/tencent/mars/xlog/Log");
    if (_c_Log == NULL) return (JniResult){.value = {.j = 0}, .exception = check_exception()};
    load_static_method(_c_Log,
      &_m_Log__d, "d", "(Ljava/lang/String;Ljava/lang/String;)V");
    if (_m_Log__d == NULL) return (JniResult){.value = {.j = 0}, .exception = check_exception()};
    (*jniEnv)->CallStaticVoidMethod(jniEnv, _c_Log, _m_Log__d, string, string1);
    return (JniResult){.value = {.j = 0}, .exception = check_exception()};
}

jmethodID _m_Log__v = NULL;
FFI_PLUGIN_EXPORT
JniResult Log__v(jobject string,jobject string1) {
    load_env();
        load_class_global_ref(&_c_Log, "com/tencent/mars/xlog/Log");
    if (_c_Log == NULL) return (JniResult){.value = {.j = 0}, .exception = check_exception()};
    load_static_method(_c_Log,
      &_m_Log__v, "v", "(Ljava/lang/String;Ljava/lang/String;)V");
    if (_m_Log__v == NULL) return (JniResult){.value = {.j = 0}, .exception = check_exception()};
    (*jniEnv)->CallStaticVoidMethod(jniEnv, _c_Log, _m_Log__v, string, string1);
    return (JniResult){.value = {.j = 0}, .exception = check_exception()};
}

jmethodID _m_Log__f1 = NULL;
FFI_PLUGIN_EXPORT
JniResult Log__f1(jobject string,jobject string1,jobject objects) {
    load_env();
        load_class_global_ref(&_c_Log, "com/tencent/mars/xlog/Log");
    if (_c_Log == NULL) return (JniResult){.value = {.j = 0}, .exception = check_exception()};
    load_static_method(_c_Log,
      &_m_Log__f1, "f", "(Ljava/lang/String;Ljava/lang/String;[Ljava/lang/Object;)V");
    if (_m_Log__f1 == NULL) return (JniResult){.value = {.j = 0}, .exception = check_exception()};
    (*jniEnv)->CallStaticVoidMethod(jniEnv, _c_Log, _m_Log__f1, string, string1, objects);
    return (JniResult){.value = {.j = 0}, .exception = check_exception()};
}

jmethodID _m_Log__e1 = NULL;
FFI_PLUGIN_EXPORT
JniResult Log__e1(jobject string,jobject string1,jobject objects) {
    load_env();
        load_class_global_ref(&_c_Log, "com/tencent/mars/xlog/Log");
    if (_c_Log == NULL) return (JniResult){.value = {.j = 0}, .exception = check_exception()};
    load_static_method(_c_Log,
      &_m_Log__e1, "e", "(Ljava/lang/String;Ljava/lang/String;[Ljava/lang/Object;)V");
    if (_m_Log__e1 == NULL) return (JniResult){.value = {.j = 0}, .exception = check_exception()};
    (*jniEnv)->CallStaticVoidMethod(jniEnv, _c_Log, _m_Log__e1, string, string1, objects);
    return (JniResult){.value = {.j = 0}, .exception = check_exception()};
}

jmethodID _m_Log__w1 = NULL;
FFI_PLUGIN_EXPORT
JniResult Log__w1(jobject string,jobject string1,jobject objects) {
    load_env();
        load_class_global_ref(&_c_Log, "com/tencent/mars/xlog/Log");
    if (_c_Log == NULL) return (JniResult){.value = {.j = 0}, .exception = check_exception()};
    load_static_method(_c_Log,
      &_m_Log__w1, "w", "(Ljava/lang/String;Ljava/lang/String;[Ljava/lang/Object;)V");
    if (_m_Log__w1 == NULL) return (JniResult){.value = {.j = 0}, .exception = check_exception()};
    (*jniEnv)->CallStaticVoidMethod(jniEnv, _c_Log, _m_Log__w1, string, string1, objects);
    return (JniResult){.value = {.j = 0}, .exception = check_exception()};
}

jmethodID _m_Log__i1 = NULL;
FFI_PLUGIN_EXPORT
JniResult Log__i1(jobject string,jobject string1,jobject objects) {
    load_env();
        load_class_global_ref(&_c_Log, "com/tencent/mars/xlog/Log");
    if (_c_Log == NULL) return (JniResult){.value = {.j = 0}, .exception = check_exception()};
    load_static_method(_c_Log,
      &_m_Log__i1, "i", "(Ljava/lang/String;Ljava/lang/String;[Ljava/lang/Object;)V");
    if (_m_Log__i1 == NULL) return (JniResult){.value = {.j = 0}, .exception = check_exception()};
    (*jniEnv)->CallStaticVoidMethod(jniEnv, _c_Log, _m_Log__i1, string, string1, objects);
    return (JniResult){.value = {.j = 0}, .exception = check_exception()};
}

jmethodID _m_Log__d1 = NULL;
FFI_PLUGIN_EXPORT
JniResult Log__d1(jobject string,jobject string1,jobject objects) {
    load_env();
        load_class_global_ref(&_c_Log, "com/tencent/mars/xlog/Log");
    if (_c_Log == NULL) return (JniResult){.value = {.j = 0}, .exception = check_exception()};
    load_static_method(_c_Log,
      &_m_Log__d1, "d", "(Ljava/lang/String;Ljava/lang/String;[Ljava/lang/Object;)V");
    if (_m_Log__d1 == NULL) return (JniResult){.value = {.j = 0}, .exception = check_exception()};
    (*jniEnv)->CallStaticVoidMethod(jniEnv, _c_Log, _m_Log__d1, string, string1, objects);
    return (JniResult){.value = {.j = 0}, .exception = check_exception()};
}

jmethodID _m_Log__v1 = NULL;
FFI_PLUGIN_EXPORT
JniResult Log__v1(jobject string,jobject string1,jobject objects) {
    load_env();
        load_class_global_ref(&_c_Log, "com/tencent/mars/xlog/Log");
    if (_c_Log == NULL) return (JniResult){.value = {.j = 0}, .exception = check_exception()};
    load_static_method(_c_Log,
      &_m_Log__v1, "v", "(Ljava/lang/String;Ljava/lang/String;[Ljava/lang/Object;)V");
    if (_m_Log__v1 == NULL) return (JniResult){.value = {.j = 0}, .exception = check_exception()};
    (*jniEnv)->CallStaticVoidMethod(jniEnv, _c_Log, _m_Log__v1, string, string1, objects);
    return (JniResult){.value = {.j = 0}, .exception = check_exception()};
}

jmethodID _m_Log__printErrStackTrace = NULL;
FFI_PLUGIN_EXPORT
JniResult Log__printErrStackTrace(jobject string,jobject throwable,jobject string1,jobject objects) {
    load_env();
        load_class_global_ref(&_c_Log, "com/tencent/mars/xlog/Log");
    if (_c_Log == NULL) return (JniResult){.value = {.j = 0}, .exception = check_exception()};
    load_static_method(_c_Log,
      &_m_Log__printErrStackTrace, "printErrStackTrace", "(Ljava/lang/String;Ljava/lang/Throwable;Ljava/lang/String;[Ljava/lang/Object;)V");
    if (_m_Log__printErrStackTrace == NULL) return (JniResult){.value = {.j = 0}, .exception = check_exception()};
    (*jniEnv)->CallStaticVoidMethod(jniEnv, _c_Log, _m_Log__printErrStackTrace, string, throwable, string1, objects);
    return (JniResult){.value = {.j = 0}, .exception = check_exception()};
}

jmethodID _m_Log__getSysInfo = NULL;
FFI_PLUGIN_EXPORT
JniResult Log__getSysInfo() {
    load_env();
        load_class_global_ref(&_c_Log, "com/tencent/mars/xlog/Log");
    if (_c_Log == NULL) return (JniResult){.value = {.j = 0}, .exception = check_exception()};
    load_static_method(_c_Log,
      &_m_Log__getSysInfo, "getSysInfo", "()Ljava/lang/String;");
    if (_m_Log__getSysInfo == NULL) return (JniResult){.value = {.j = 0}, .exception = check_exception()};
    jobject _result = (*jniEnv)->CallStaticObjectMethod(jniEnv, _c_Log, _m_Log__getSysInfo);
    return to_global_ref_result(_result);
}

jmethodID _m_Log__openLogInstance = NULL;
FFI_PLUGIN_EXPORT
JniResult Log__openLogInstance(int32_t i,int32_t i1,jobject string,jobject string1,jobject string2,int32_t i2) {
    load_env();
        load_class_global_ref(&_c_Log, "com/tencent/mars/xlog/Log");
    if (_c_Log == NULL) return (JniResult){.value = {.j = 0}, .exception = check_exception()};
    load_static_method(_c_Log,
      &_m_Log__openLogInstance, "openLogInstance", "(IILjava/lang/String;Ljava/lang/String;Ljava/lang/String;I)Lcom/tencent/mars/xlog/Log$LogInstance;");
    if (_m_Log__openLogInstance == NULL) return (JniResult){.value = {.j = 0}, .exception = check_exception()};
    jobject _result = (*jniEnv)->CallStaticObjectMethod(jniEnv, _c_Log, _m_Log__openLogInstance, i, i1, string, string1, string2, i2);
    return to_global_ref_result(_result);
}

jmethodID _m_Log__closeLogInstance = NULL;
FFI_PLUGIN_EXPORT
JniResult Log__closeLogInstance(jobject string) {
    load_env();
        load_class_global_ref(&_c_Log, "com/tencent/mars/xlog/Log");
    if (_c_Log == NULL) return (JniResult){.value = {.j = 0}, .exception = check_exception()};
    load_static_method(_c_Log,
      &_m_Log__closeLogInstance, "closeLogInstance", "(Ljava/lang/String;)V");
    if (_m_Log__closeLogInstance == NULL) return (JniResult){.value = {.j = 0}, .exception = check_exception()};
    (*jniEnv)->CallStaticVoidMethod(jniEnv, _c_Log, _m_Log__closeLogInstance, string);
    return (JniResult){.value = {.j = 0}, .exception = check_exception()};
}

jmethodID _m_Log__getLogInstance = NULL;
FFI_PLUGIN_EXPORT
JniResult Log__getLogInstance(jobject string) {
    load_env();
        load_class_global_ref(&_c_Log, "com/tencent/mars/xlog/Log");
    if (_c_Log == NULL) return (JniResult){.value = {.j = 0}, .exception = check_exception()};
    load_static_method(_c_Log,
      &_m_Log__getLogInstance, "getLogInstance", "(Ljava/lang/String;)Lcom/tencent/mars/xlog/Log$LogInstance;");
    if (_m_Log__getLogInstance == NULL) return (JniResult){.value = {.j = 0}, .exception = check_exception()};
    jobject _result = (*jniEnv)->CallStaticObjectMethod(jniEnv, _c_Log, _m_Log__getLogInstance, string);
    return to_global_ref_result(_result);
}

jfieldID _f_Log__toastSupportContext = NULL;
FFI_PLUGIN_EXPORT
JniResult get_Log__toastSupportContext() {
    load_env();
        load_class_global_ref(&_c_Log, "com/tencent/mars/xlog/Log");
    if (_c_Log == NULL) return (JniResult){.value = {.j = 0}, .exception = check_exception()};
    load_static_field(_c_Log, &_f_Log__toastSupportContext, "toastSupportContext",
      "Landroid/content/Context;");
    jobject _result = (*jniEnv)->GetStaticObjectField(jniEnv, _c_Log, _f_Log__toastSupportContext);
    return to_global_ref_result(_result);
}

FFI_PLUGIN_EXPORT
JniResult set_Log__toastSupportContext(jobject value) {
    load_env();
        load_class_global_ref(&_c_Log, "com/tencent/mars/xlog/Log");
    if (_c_Log == NULL) return (JniResult){.value = {.j = 0}, .exception = check_exception()};
    load_static_field(_c_Log, &_f_Log__toastSupportContext, "toastSupportContext",
      "Landroid/content/Context;");
    (*jniEnv)->SetStaticObjectField(jniEnv, _c_Log, _f_Log__toastSupportContext, value);
    return (JniResult){.value = {.j = 0}, .exception = check_exception()};
}

